export default Types = {
    LOGIN: "LOGIN",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    
    GET_USER_DETAILS: "GET_USER_DETAILS",
    GET_USER_DETAILS_SUCCESS: "GET_USER_DETAILS_SUCCESS",
    GET_USER_DETAILS_FAILDED: "GET_USER_DETAILS_FAILDED",
  
      GET_ADDRESS: 'GET_ADDRESS',
      GET_ADDRESS_SUCCESS: 'GET_ADDRESS_SUCCESS',
      GET_ADDRESS_FAIL: 'GET_ADDRESS_FAIL',
  
      CREATE_ADDRESS: 'CREATE_ADDRESS',
      CREATE_ADDRESS_SUCCESS: 'CREATE_ADDRESS_SUCCESS',
      CREATE_ADDRESS_FAIL: 'CREATE_ADDRESS_FAIL',
  
      UPDATE_ADDRESS: 'UPDATE_ADDRESS',
      UPDATE_ADDRESS_SUCCESS: 'UPDATE_ADDRESS_SUCCESS',
      UPDATE_ADDRESS_FAIL: 'UPDATE_ADDRESS_FAIL',
  
      LOGIN_OTP: 'LOGIN_OTP',
      LOGIN_OTP_SUCCESS: 'LOGIN_OTP_SUCCESS',
      LOGIN_OTP_FAIL: 'LOGIN_OTP_FAIL',
  
      SIGNUP: 'SIGNUP',
      SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
      SIGNUP_FAIL: 'SIGNUP_FAIL',
  
      CHECK_TOKEN: 'CHECK_TOKEN',
      CHECK_TOKEN_SUCCESS: 'CHECK_TOKEN_SUCCESS',
      CHECK_TOKEN_FAIL: 'CHECK_TOKEN_FAIL',
  
      CHANGE_PASS: 'CHANGE_PASS',
      CHANGE_PASS_SUCCESS: 'CHANGE_PASS_SUCCESS',
      CHANGE_PASS_FAIL: 'CHANGE_PASS_FAIL',
  
      FORGOT_PASS: 'FORGOT_PASS',
      FORGOT_PASS_SUCCESS: 'FORGOT_PASS_SUCCESS',
      FORGOT_PASS_FAIL: 'FORGOT_PASS_FAIL',
  
      LOGOUT: 'LOGOUT',
      LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  
      UPDATE_USER_NAME: 'UPDATE_USER_NAME',
      UPDATE_USER_NAME_SUCCESS: 'UPDATE_USER_NAME_SUCCESS',
      UPDATE_USER_NAME_FAIL: 'UPDATE_USER_NAME_FAIL',
  
      GET_PROFILES: 'GET_PROFILES',
      GET_PROFILES_SUCCESS: 'GET_PROFILES_SUCCESS',
      GET_PROFILES_FAIL: 'GET_PROFILES_FAIL',
  
      GET_OTP: 'GET_OTP',
      GET_OTP_SUCCESS: 'GET_OTP_SUCCESS',
      GET_OTP_FAIL: 'GET_OTP_FAIL',
  
      GET_APPLY_ROLES: 'GET_APPLY_ROLES',
      GET_APPLY_ROLES_SUCCESS: 'GET_APPLY_ROLES_SUCCESS',
      GET_APPLY_ROLES_FAIL: 'GET_APPLY_ROLES_FAIL',
  
      VERIFY_OTP: 'VERIFY_OTP',
      VERIFY_OTP_SUCCESS: 'VERIFY_OTP_SUCCESS',
      VERIFY_OTP_FAIL: 'VERIFY_OTP_FAIL',
  
  
      UPDATE_PROFILES: 'UPDATE_PROFILES',
      UPDATE_PROFILES_SUCCESS: 'UPDATE_PROFILES_SUCCESS',
      UPDATE_PROFILES_FAIL: 'UPDATE_PROFILES_FAIL',
  
      UPDATE_USER_AVATAR: 'UPDATE_USER_AVATAR',
      UPDATE_USER_AVATAR_SUCCESS: 'UPDATE_USER_AVATAR_SUCCESS',
      UPDATE_USER_AVATAR_FAIL: 'UPDATE_USER_AVATAR_FAIL',
  
      UPDATE_PROFILES_IMAGE: 'UPDATE_PROFILES_IMAGE',
      UPDATE_PROFILES_IMAGE_SUCCESS: 'UPDATE_PROFILES_IMAGE_SUCCESS',
      UPDATE_PROFILES_IMAGE_FAIL: 'UPDATE_PROFILES_IMAGE_FAIL',
    
  };